export const API_CONSTANT = {
  USER: "users",
  AUTH: "auth",
  LOGIN: "login",
  BRANCH: "branches",
  DEPARTMENT: "departments",
  STAFF: "staffs",
  SUPPLIER: "suppliers",
  CUSTOMER: "customers",
  ALL: "all",
  TOGGLE_STATUS: "toggle-status",
  ROLE: "roles",
  BY_BRANCH: "by-branch",
  FEATURE: "features",
  ASSIGN_ROLES: "assign-roles",
  PRICE_GROUP: "price-groups",
  CUSTOMER_TYPE: "customer-types",
  VARIATION: "variations",
  UOM: "unit-of-measurements",
  UOM_CONVERSION: "uom-conversions",
  CURRENCY: "currencies",
} as const;
