export const API_CONSTANT = {
  USER: "users",
  AUTH: "auth",
  LOGIN: "login",
  BRANCH: "branches",
  DEPARTMENT: "departments",
  STAFF: "staffs",
  SUPPLIER: "suppliers",
  CUSTOMER: "customers",
  ALL: "all",
  TOGGLE_STATUS: "toggle-status",
  ROLE: "roles",
  BY_BRANCH: "by-branch",
  FEATURE: "features",
  ASSIGN_ROLES: "assign-roles",
} as const;
